name: Serenity API Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Java 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      # 3. Compilar y ejecutar pruebas
      - name: Run Serenity Tests
        run: mvn clean verify -B

      # 4. Publicar reporte Serenity como artefacto
      - name: Upload Serenity Report
        uses: actions/upload-artifact@v3
        with:
          name: serenity-report
          path: target/site/serenity